#%RAML 0.8
---
title: JC-Interface - Lookup Code Services
version: 0.0.1
protocols: [HTTPS]
baseUri:
mediaType: application/json
securedBy: [basic]

securitySchemes:
  - basic:
      type: Basic Authentication

schemas: 

  - lookupCode: |
     {
       "$schema": "http://json-schema.org/draft-04/schema#",
       "type": "object",
       "description": "A code value as defined in the JUSTIN/CEIS web services.",
       "properties": {
         "codeType": {
           "id": "codeType",
           "type": "string"
         },
         "code": {
           "id": "code",
           "type": "string"
         },
         "shortDesc": {
           "id": "shortDesc",
           "type": "string"
         },
         "longDesc": {
           "id": "longDesc",
           "type": "string"
         },
         "flex": {
           "id": "flex",
           "type": "string"
         }
       },
       "required": [
         "codeType",
         "code",
         "shortDesc",
         "longDesc",
         "flex"
       ]
     }

  - lookupCodes: |
     {
       "$schema": "http://json-schema.org/draft-04/schema#",
       "type": "array",
       "description": "lookupCodes",
       "items": { "$ref": "lookupCode" }
     }

resourceTypes:
  - readOnlyFilteredCollection:
      get:
        description: |
          Get a list of available <<resourcePathName>>.
        queryParameters:
          flexFilter:
            displayName: The flex code on which to filter the <<resourcePathName>>.
            type: string
            required: false        
        responses:
          200:
            body:
              application/json:
                schema: lookupCodes
          404:
            body:
              application/json:
                example: |
                  {"message": "No items matching the given criteria were found."}

  - readOnlyCollection:
      get:
        description: |
          Get a list of available <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                schema: lookupCodes
          404:
            body:
              application/json:
                example: |
                  {"message": "No items matching the given criteria were found."}

  - readOnlyCollectionItem:
      get:
        description: |
          Get the specific <<resourcePathName|!singularize>>.
        responses:
          200:
            body:
              application/json:
                schema: lookupCode
          404:
            body:
              application/json:
                example: |
                  {"message": "No items matching the given criteria were found."}

/codes:
  displayName: Lookup Code Resources
  description: |
    A set of resources that provides lookup code information from Justin/CEIS.
  
  /adjudicators:
    type:
      readOnlyCollection:
    /{adjudicatorId}:
      type:
        readOnlyCollectionItem:
  
  /agencyLocations:
    type:
      readOnlyCollection:
  
  /asset:
    /roleCombos:
      type:
        readOnlyCollection:
      /{roleComboId}:
        type:
          readOnlyFilteredCollection:  
    /usageRules:
      type:
        readOnlyCollection:
      /{assetUsageRuleId}:  
        type:
          readOnlyCollectionItem:
  
  /crown:
    /assignments:
      type:
        readOnlyCollection:
      /{assignmentId}:
        type:
          readOnlyCollectionItem:
    /federal:
      /courts:
        type:
          readOnlyCollection:
        /{courtId}:
          type:
            readOnlyCollectionItem:
    /provincial:
      /courts:
        type:
          readOnlyCollection:
        /{courtId}:
          type:
            readOnlyCollectionItem:      
    
  /court:
    /classes:
      type:
        readOnlyCollection:
      /{classeId}:
        type:
          readOnlyCollectionItem:
    /divisions:
      type:
        readOnlyCollection:
      /{divisionId}:
        type:
          readOnlyCollectionItem:
    /levels:
      type:
        readOnlyCollection:
      /{levelId}:
        type:
          readOnlyCollectionItem:
  
  /devices:
    type:
      readOnlyCollection:
    /{deviceId}:
      type:
        readOnlyCollectionItem:
  
  /documents:
    type:
      readOnlyCollection:
    /{documentId}:
      type:
        readOnlyCollectionItem:
  
  /file:
    /complexities:
      type:
        readOnlyCollection:
      /{complexityId}:
        type:
          readOnlyCollectionItem:
  
  /findings:
    type:
      readOnlyCollection:
    /{findingId}:
      type:
        readOnlyCollectionItem:

  /hearing:
    /restrictions:
      type:
        readOnlyCollection:
      /{restrictionId}:
        type:
          readOnlyCollectionItem:
  
  /roles:
    type:
      readOnlyCollection:
    /{roleId}:
      type:
        readOnlyCollectionItem:
  
  /participant:
    /roles:
      type:
        readOnlyCollection:
      /{roleId}:
        type:
          readOnlyCollectionItem:
  
  /trial:
    /collapse:
      /reasons:
        type:
          readOnlyCollection:
        /{reasonId}:
          type:
            readOnlyFilteredCollection:
    /proceeded:
      /codes:
        type:
          readOnlyCollection:
        /{codeId}:
          type:
            readOnlyCollectionItem:
    
  /witness:
    /roles:
      type:
        readOnlyCollection:
      /{roleId}:
        type:
          readOnlyCollectionItem:

  /civil:
    /assets:
      type:
        readOnlyCollection:
      /{assetId}:
        type:
          readOnlyCollectionItem:
    /appearance:
      /duration:
        type:
          readOnlyCollection:
        /{durationId}:
          type:
            readOnlyCollectionItem:
      /reasons:
        type:
          readOnlyCollection:
        /{reasonId}:
          type:
            readOnlyCollectionItem:
      /results:
        type:
          readOnlyCollection:
        /{resultId}:
          type:
            readOnlyCollectionItem:
      /statuses:
        type:
          readOnlyCollection:
        /{statusId}:
          type:
            readOnlyCollectionItem:
    /dateDeclinedBy:
      type:
        readOnlyCollection:
      /{dateDeclinedById}:
        type:
          readOnlyCollectionItem:
    /document:
      /issueTypes:
        type:
          readOnlyCollection:
        /{code}:
          type:
            readOnlyCollectionItem:
      
    /priority:
      /markers:
        type:
          readOnlyCollection:
        /{markerId}:
          type:
            readOnlyCollectionItem:
    /pastAppearance:
      /partyAppearanceMethod:
        /partyAttendanceTypes:
          type:
            readOnlyCollection:
          /{partyAppearanceMethod}:
            type:
              readOnlyCollectionItem:
        /counsel:
          type:
            readOnlyCollection:
          /{partyAppearanceMethod}:
            type:
              readOnlyCollectionItem:
  
  /criminal:
    /assets:
      type:
        readOnlyCollection:
      /{assetId}:
        type:
          readOnlyCollectionItem:
    /sentences:
      type:
        readOnlyCollection:
      /{sentenceId}:
        type:
          readOnlyCollectionItem:
    /banStatutes:
      type:
        readOnlyCollection:
      /{banStatuteId}:
        type:
          readOnlyCollectionItem:
    /appearance:
      /duration:
        type:
          readOnlyCollection:
        /{durationId}:
          type:
            readOnlyCollectionItem:
      /reasons:
        type:
          readOnlyCollection:
        /{reasonId}:
          type:
            readOnlyCollectionItem:
      /results:
        type:
          readOnlyCollection:
        /{resultId}:
          type:
            readOnlyCollectionItem:
      /statuses:
        type:
          readOnlyCollection:
        /{statusId}:
          type:
            readOnlyCollectionItem:
    /dateDeclinedBy:
      type:
        readOnlyCollection:
      /{dateDeclinedById}:
        type:
          readOnlyCollectionItem:
    /priority:
      /markers:
        type:
          readOnlyCollection:
        /{markerId}:
          type:
            readOnlyCollectionItem:
    /pastAppearance:
      /partyAppearanceMethod:
        /accused:
          type:
            readOnlyCollection:
          /{partyAppearanceMethod}:
            type:
              readOnlyCollectionItem:
        /accusedCounsel:
          type:
            readOnlyCollection:
          /{partyAppearanceMethod}:
            type:
              readOnlyCollectionItem:
        /adjudicator:
          type:
            readOnlyCollection:
          /{partyAppearanceMethod}:
            type:
              readOnlyCollectionItem:
        /crown:
          type:
            readOnlyCollection:
          /{partyAppearanceMethod}:
            type:
              readOnlyCollectionItem:
            