#%RAML 0.8
---
title: JC-Interface - User Service
version: 0.0.1
protocols: [HTTPS]

mediaType: application/json
securedBy: [basic]

securitySchemes:
  - basic:
      type: Basic Authentication

schemas:

  - loginHistory: | 
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "loginDtm" : {
            "type" : "string"
          },
          "loginDayOfWeek" : {
            "type" : "string"
          },
          "deviceNm" : {
            "type" : "string"
          },
          "ipAddressTxt" : {
            "type" : "string"
          }
        }
      } 
      
  - getUserLoginResponseType: | 
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "responseCd" : {
            "type" : "string"
          },
          "responseMessageTxt" : {
            "type" : "string"
          },
          "userPartId" : {
            "type" : "string"
          },
          "userDefaultAgencyCd" : {
            "type" : "string"
          },
          "userNm" : {
            "type" : "string"
          },
          "loginHistory" : {
            "type" : "array",
            "items" : { "$ref" : "loginHistory" }
          }
        }
      }    

/user:
  displayName: Court User Resources
  
  /getUserLogin:
    get:
      description: |
        Gets the participant id for a specific domain, user guid and userid. 
      headers:
        domainNm:
          description: The domain name of the user
          type: string
          required: false
        domainUserGuid:
          description: The user guid of the user
          type: string
          required: true
        domainUserId:
          description: The user id of the user
          type: string
          required: false
        deviceNm:
          displayName: applicationCd
          description: The device name
          type: string
          required: false
        ipAddressTxt:
          displayName: applicationCd
          description: Ip address
          type: string
          required: false
        temporaryAccessGuid:
          displayName: applicationCd
          description: Temporary access guid
          type: string
          required: false
      responses:
        200:
          body:
            application/json:
              schema: getUserLoginResponseType
        404:
          body:
            application/json:
              example: |
                {"message": "No items matching the given criteria were found."}